server:
  port: 8081

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./data/h2/testdb;AUTO_SERVER=TRUE;MODE=MySQL;
      driver-class-name: org.h2.Driver
      username: sa
      password: sa
  h2:
    console:
      enabled: true
      path: /h2-db
  jpa:
    properties:
      hibernate:
        format_sql : true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          info
security:
  jwt:
    secret-key: test-secret-02-a12zs33zaedfeeaaesef
    expire-time: 99999999   # 30M
    auth-key : test-demon-auth-key